# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20170409_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expires_in',
            field=models.PositiveIntegerField(default=86402),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='custom_auth.ApplicationUser'),
        ),
    ]
