# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_auto_20170425_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='last_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
